data:
  type: 'Original' # or Ground truth/
  in_size: 2048
  out_size: 224
  crop_pct: 0.109375
  mean_imgnet: [0.485, 0.456, 0.406] # from timm.data.constants
  std_imgnet: [0.229, 0.224, 0.225] # from timm.data.constants
  interpolate: 'bicubic'
  nsamples: 600
  train_eval_split: .80

training:
  type: 'finetune'
  batch_size: 32 
  n_classes: 4
  max_epch: 25 # for testing 
  exp_epochs: 50
  accum_iter: 1 # args
  weight_decay: 0.05
  layer_decay: 0.75
  min_lr: 1e-6
  lr: 1e-4
  warmup_epochs: 10 
  checkpoint: './RETFound_cfp_weights.pth'
  folds: 5 # for testing 

  lr_scheduler:
    use: True
    total_steps: ${..max_steps}
    pct_start: 0.005
    div_factor: 25 # init_lr = max_lr / div_factor
    final_div_factor: 10000 # final_lr = max_lr / final_div_factor (this is different from Pytorch' OneCycleLR param)


  logging:
    log_dir: './train_logs/'
    task: 'retfundfives_amd_finetune'
    print_freq: 5
    name: "OriginalDS"

  checkpointing: 
    out_dir: './mdl_ckpts/'
    task: 'retfundfives'

testing:
  n_classes: 2 
  batch_size: 200  
  task: 'Original_finetune_retfundfives_amd_finetune'
  folds: 5
   